### ISSUE TITLE
Please Help Me Run the Project I'm getting the followin error

### ISSUE THREAD

**Issue by sparshgahlot1** [rajeshmn47/dream-11-clone-mern-stack#1]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-alert@7.0.3
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.9.0
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.9.0" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.10.5
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.10.5" from the root project
npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!     3 more (@mui/material, @mui/styled-engine, @mui/system)
npm ERR!   29 more (@emotion/styled, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1 || ^17" from react-alert@7.0.3
npm ERR! node_modules/react-alert
npm ERR!   react-alert@"^7.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.1 || ^17" from react-alert@7.0.3
npm ERR!   node_modules/react-alert
npm ERR!     react-alert@"^7.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\spars\AppData\Local\npm-cache\_logs\2023-06-15T09_11_40_854Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\spars\AppData\Local\npm-cache\_logs\2023-06-15T09_11_40_854Z-debug-0.log

**Comment by rajeshmn47** [comment]
> npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: react-alert@7.0.3 npm ERR! Found: react@18.1.0 npm ERR! node_modules/react npm ERR! react@"^18.1.0" from the root project npm ERR! peer react@">=16.8.0" from @emotion/react@11.9.0 npm ERR! node_modules/@emotion/react npm ERR! @emotion/react@"^11.9.0" from the root project npm ERR! peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.10.5 npm ERR! node_modules/@emotion/styled npm ERR! @emotion/styled@"^11.10.5" from the root project npm ERR! 3 more (@mui/material, @mui/styled-engine, @mui/system) npm ERR! 3 more (@mui/material, @mui/styled-engine, @mui/system) npm ERR! 29 more (@emotion/styled, ...) npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^16.8.1 || ^17" from react-alert@7.0.3 npm ERR! node_modules/react-alert npm ERR! react-alert@"^7.0.3" from the root project npm ERR! npm ERR! Conflicting peer dependency: react@17.0.2 npm ERR! node_modules/react npm ERR! peer react@"^16.8.1 || ^17" from react-alert@7.0.3 npm ERR! node_modules/react-alert npm ERR! react-alert@"^7.0.3" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! npm ERR! For a full report see: npm ERR! C:\Users\spars\AppData\Local\npm-cache_logs\2023-06-15T09_11_40_854Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\spars\AppData\Local\npm-cache_logs\2023-06-15T09_11_40_854Z-debug-0.log

Run npm i --force

**Comment by sparshgahlot1** [comment]
When I do npm start I get this error:

PS C:\Users\spars\Downloads\Compressed\dream-11-clone-mern-stack-main> npm start

> dreameleven@0.1.0 start
> DISABLE_ESLINT_PLUGIN=true REACT_APP_API=local react-scripts start

'DISABLE_ESLINT_PLUGIN' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\spars\Downloads\Compressed\dream-11-clone-mern-stack-main>

**Comment by rajeshmn47** [comment]
"start": "REACT_APP_API=local react-scripts start", use this command in the package.json

**Comment by MBSA-INFINITY** [comment]
for me `"start": "react-scripts start"`  works. This `"start": "REACT_APP_API=local react-scripts start"` throws any error for me!

**Comment by rajeshmn47** [comment]
DISABLE_ESLINT_PLUGIN=true remove it
